### PR TITLE
In addition to adding a test file to S3, we will also try to delete it

### PR DESCRIPTION
**Pull request by antonrd**
This is to confirm that delete operations are possible.

### CODE REVIEW

**Comment by filiphaftek** [comment]
👍

**Comment by wojtih** [comment]
👍

**Comment by antonrd** [comment]
I forgot to change the name of the file created, let me add that in the PR before merging.

**Comment by filiphaftek** [comment]
@antonrd thanks for that. But is there a chance that this file name contains app name as well in case that more than one application is using the same bucket? But pls do not consider any AH specific solutions, as we plan to make public PR from this fork soon :)

**Comment by antonrd** [comment]
@filiphaftek currently I don't see in the `CustomHealthChecks` a variable containing the app name. Probably the class constructor needs to be changes to accept that and then the value must be passed in all places where it's used. However, this is going to require some more work and for this I would prefer to have a Jira card or let someone who built this to modify it.

**Pull request merged**
